### ISSUE TITLE
No component factory found for NgGridPlaceholder

### ISSUE THREAD

**Issue by slimj** [BTMorton/angular2-grid#140]
I found a problem when adding  "angular2-grid": "^0.11.0",

knowing that in app.module.ts  i had put:
import { NgGrid, NgGridItem , NgGridItemEvent} from 'angular2-grid';

and 

/**
- `AppModule` is the main entry point into Angular2's bootstraping process
  */
  @NgModule({
  bootstrap: [ App ],
  declarations: [
    App,
    NgGrid,
    NgGridItem,
  ],

here is  my template:

<div class="grid" [ngGrid]="gridProperties">
    <div   class="grid-item" *ngFor="let d of devices" [(ngGridItem)]="d.gridProp" (onDragStop) ="onDragStop($event, this)">
    {{d.gridProp.col}},{{d.gridProp.row}} <br>
    {{d.dbDevice.deviceId}}<br>
    {{d.dbDevice.description}}
    </div>
</div>

and i have got this error:

vendor.bundle.js:30869Error: No component factory found for NgGridPlaceholder
    at NoComponentFactoryError.Error (native)
    at NoComponentFactoryError.BaseError [as constructor](http://localhost:3000/vendor.bundle.js:31452:34)
    at new NoComponentFactoryError (http://localhost:3000/vendor.bundle.js:32328:16)
    at _NullComponentFactoryResolver.resolveComponentFactory (http://localhost:3000/vendor.bundle.js:32337:15)
    at NgModuleInjector.CodegenComponentFactoryResolver.resolveComponentFactory (http://localhost:3000/vendor.bundle.js:32362:35)
    at NgGrid._createPlaceholder (http://localhost:3000/main.bundle.js:8775:53)
    at NgGrid._dragStart (http://localhost:3000/main.bundle.js:8110:18)
    at NgGrid._onMouseMove (http://localhost:3000/main.bundle.js:8132:18)
    at DebugAppView._View_Layout0._handle_mousemove_9_1 (Layout.ngfactory.js:170:32)
    at http://localhost:3000/vendor.bundle.js:33719:24
    at http://localhost:3000/vendor.bundle.js:47911:36
    at http://localhost:3000/vendor.bundle.js:48013:111
    at ZoneDelegate.invoke (http://localhost:3000/polyfills.bundle.js:15170:28)
    at Object.onInvoke (http://localhost:3000/vendor.bundle.js:36760:37)
    at ZoneDelegate.invoke (http://localhost:3000/polyfills.bundle.js:15169:34)
    at Zone.runGuarded (http://localhost:3000/polyfills.bundle.js:15077:47)
    at NgZoneImpl.runInnerGuarded (http://localhost:3000/vendor.bundle.js:36789:78)
    at NgZone.runGuarded (http://localhost:3000/vendor.bundle.js:36693:73)
    at HTMLDivElement.outsideHandler (http://localhost:3000/vendor.bundle.js:48013:79)
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.bundle.js:15203:37)
    at Zone.runTask (http://localhost:3000/polyfills.bundle.js:15103:47)
    at HTMLDivElement.ZoneTask.invoke (http://localhost:3000/polyfills.bundle.js:15271:33)

**Comment by slimj** [comment]
i have imported  NgGridModule and that fixes that up.
import { NgGridModule } from 'angular2-grid';
  imports: [ // import Angular's modules
    BrowserModule,
    FormsModule,
    HttpModule,
    NgGridModule,
 RouterModule.forRoot(ROUTES, { useHash: true }),
    ...MATERIAL_DIRECTIVES
  ],

**Comment by BTMorton** [comment]
Yeah, it's the NgGridModule. I've now updated the Readme to reflect the changes
