### ISSUE TITLE
AOT issues with compiler@2.2.1

### ISSUE THREAD

**Issue by jskrzypek** [BTMorton/angular2-grid#175]
I'm getting these errors with `ngc` at `2.2.1`
```
Error: Error at ~/my-aot-project/aot/node_modules/angular2-grid/dist/directives/NgGrid.ngfactory.ts:62:48: Property '_onMouseDown' is private and only accessible within class 'NgGrid'.
Error at ~/my-aot-project/aot/node_modules/angular2-grid/dist/directives/NgGrid.ngfactory.ts:66:48: Property '_onMouseMove' is private and only accessible within class 'NgGrid'.
Error at ~/my-aot-project/aot/node_modules/angular2-grid/dist/directives/NgGrid.ngfactory.ts:70:48: Property '_onMouseUp' is private and only accessible within class 'NgGrid'.
Error at ~/my-aot-project/aot/node_modules/angular2-grid/dist/directives/NgGrid.ngfactory.ts:74:48: Property '_onMouseDown' is private and only accessible within class 'NgGrid'.
Error at ~/my-aot-project/aot/node_modules/angular2-grid/dist/directives/NgGrid.ngfactory.ts:78:48: Property '_onMouseMove' is private and only accessible within class 'NgGrid'.
Error at ~/my-aot-project/aot/node_modules/angular2-grid/dist/directives/NgGrid.ngfactory.ts:82:48: Property '_onMouseUp' is private and only accessible within class 'NgGrid'.
Error at ~/my-aot-project/aot/node_modules/angular2-grid/dist/directives/NgGrid.ngfactory.ts:86:48: Property '_onResize' is private and only accessible within class 'NgGrid'.
Error at ~/my-aot-project/aot/node_modules/angular2-grid/dist/directives/NgGrid.ngfactory.ts:90:48: Property '_onMouseMove' is private and only accessible within class 'NgGrid'.
Error at ~/my-aot-project/aot/node_modules/angular2-grid/dist/directives/NgGrid.ngfactory.ts:94:48: Property '_onMouseUp' is private and only accessible within class 'NgGrid'.
```

I think all of the methods used in the `host` of the `NgGrid` directive might need to be declared as public for AOT. I'm going to try changing this and report back.

**Comment by jskrzypek** [comment]
yup that fixes it, making a pr

**Comment by BTMorton** [comment]
Weird... I don't think I've run into this with my (admittedly limited) testing of AOT. Good spot!
