### ISSUE TITLE
Not compatible with angular 2.0.0-rc.0

### ISSUE THREAD

**Issue by jvendryes** [BTMorton/angular2-grid#75]
Hello angular2-grid team!

With the changes from 2.0.0-beta.17 to 2.0.0-rc.0, some rework needs to happen in regards to how you are installing and interfacing with Angular2.

At the end of the day, the required changes become as simple as:
`from '@angular/core';` instead of `from 'angular2/core';`

I've started to do a PR to update it myself, however I'm currently fighting some of the other aspects in the repo (tests/gulp/etc...)

Nice work and thanks!

**Comment by BTMorton** [comment]
Aha! A release at last! Cool, thanks for letting me know. I'll try to address the changes this evening, but if you beat me to it, thanks very much!

Oh, and feel free to ignore the tests, they haven't been updated in a while and were never complete anyway... I really need to get on that...

**Comment by jvendryes** [comment]
Dang that was fast! All works again, thanks 👍

**Comment by Luchillo** [comment]
That update in the dependency was a bit unexpected, i'm getting this kind of error after changing the dependecy and adding the `@angular/core` one:
```sh
vendor.bundle.js:42348Error: Uncaught (in promise): No Directive annotation found on NgGrid
    at resolvePromise (http://localhost:50002/js/vendor.bundle.js:42423:33)
    at http://localhost:50002/js/vendor.bundle.js:42459:19
    at ZoneDelegate.invokeTask (http://localhost:50002/js/vendor.bundle.js:42241:39)
    at Zone.runTask (http://localhost:50002/js/vendor.bundle.js:42141:49)
    at drainMicroTaskQueue (http://localhost:50002/js/vendor.bundle.js:42359:37)
    at run (http://localhost:50002/js/polyfills.bundle.js:5549:23)
    at http://localhost:50002/js/polyfills.bundle.js:5562:29
    at MutationObserver.flush (http://localhost:50002/js/polyfills.bundle.js:4039:10)consoleError @ vendor.bundle.js:42348_loop_1 @ vendor.bundle.js:42375drainMicroTaskQueue @ vendor.bundle.js:42379run @ polyfills.bundle.js:5549(anonymous function) @ polyfills.bundle.js:5562flush @ polyfills.bundle.js:4039
```

**Comment by Luchillo** [comment]
Oh ok i think i see the error, i have a package that still uses `Angular-2.0.0-beta.16` so updating to `0.7.0` makes no sense.
